### ISSUE TITLE
End up with no sitemaps directory when we reboot the box

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#139]
When we reboot the boxes, we end up nuking the sitemaps directories.

```
Warning : `load_model` does not return WordVectorModel or SupervisedModel any more, but a `FastText` object which is very similar.
INFO:     Started server process [16]
INFO:     Waiting for application startup.
2022-03-17 21:25:32,665 INFO   uvicorn.error serve():64   Started server process [16]
2022-03-17 21:25:32,665 INFO   uvicorn.error startup():26   Waiting for application startup.
INFO:     Application startup complete.
2022-03-17 21:25:33,347 INFO   uvicorn.error startup():38   Application startup complete.
2022-03-17 21:25:33,348 INFO   uvicorn.error _log_started_message():199  Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     Uvicorn running on http://0.0.0.0:8000 (Press CTRL+C to quit)
INFO:     172.19.0.1:51866 - "GET /sesar/sitemaps/sitemap-index.xml HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/fastapi/applications.py", line 199, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/sessions.py", line 75, in __call__
    await self.app(scope, receive, send_wrapper)
  File "/usr/local/lib/python3.10/site-packages/starlette/middleware/cors.py", line 78, in __call__
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/routing.py", line 390, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.10/site-packages/starlette/staticfiles.py", line 93, in __call__
    await self.check_config()
  File "/usr/local/lib/python3.10/site-packages/starlette/staticfiles.py", line 189, in check_config
    raise RuntimeError(
RuntimeError: StaticFiles directory '/app/isb_web/sitemaps' does not exist.
```

We should map the sitemaps directories to persistent volumes on the host so they stick around after a reboot.

**Comment by dannymandel** [comment]
I think this is fixed.
