### ISSUE TITLE
Bug when running heatmap code against empty db

### ISSUE THREAD

**Issue by dannymandel** [isamplesorg/isamples_inabox#65]
In the process of bringing up the iSB Docker container, I noticed that we run into a 500 error when running the heatmaps against an empty index.  Probably not likely in practice, but we should fix it:

```
isamples_inabox_1  | ERROR:uvicorn.error:Exception in ASGI application
isamples_inabox_1  | Traceback (most recent call last):
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/protocols/http/httptools_impl.py", line 398, in run_asgi
isamples_inabox_1  |     result = await app(self.scope, self.receive, self.send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
isamples_inabox_1  |     return await self.app(scope, receive, send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/applications.py", line 199, in __call__
isamples_inabox_1  |     await super().__call__(scope, receive, send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/applications.py", line 112, in __call__
isamples_inabox_1  |     await self.middleware_stack(scope, receive, send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 181, in __call__
isamples_inabox_1  |     raise exc from None
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/errors.py", line 159, in __call__
isamples_inabox_1  |     await self.app(scope, receive, _send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/middleware/cors.py", line 78, in __call__
isamples_inabox_1  |     await self.app(scope, receive, send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
isamples_inabox_1  |     raise exc from None
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/exceptions.py", line 71, in __call__
isamples_inabox_1  |     await self.app(scope, receive, sender)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 580, in __call__
isamples_inabox_1  |     await route.handle(scope, receive, send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 241, in handle
isamples_inabox_1  |     await self.app(scope, receive, send)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/starlette/routing.py", line 52, in app
isamples_inabox_1  |     response = await func(request)
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 216, in app
isamples_inabox_1  |     raw_response = await run_endpoint_function(
isamples_inabox_1  |   File "/usr/local/lib/python3.9/site-packages/fastapi/routing.py", line 149, in run_endpoint_function
isamples_inabox_1  |     return await dependant.call(**values)
isamples_inabox_1  |   File "/app/./isb_web/main.py", line 295, in get_things_geojson_heatmap
isamples_inabox_1  |     results = isb_solr_query.solr_geojson_heatmap(
isamples_inabox_1  |   File "/app/./isb_web/isb_solr_query.py", line 93, in solr_geojson_heatmap
isamples_inabox_1  |     d_lat = hm["maxY"] - hm["minY"]
isamples_inabox_1  | KeyError: 'maxY'
```

**Comment by dannymandel** [comment]
I don't think we are even using this code anymore.  Closing.
